" INSTALL vim-enhanced IN FEDORA.
" Install vim-plug(Plugin Manager) => https://github.com/junegunn/vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Put plugin here

Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } } " Markdown Preview
Plug 'sheerun/vim-polyglot' " Syntax Highlighting
Plug 'pseewald/vim-anyfold' " Language agnostic plugin for folding and motion based on indentation
Plug 'vim-scripts/indentpython.vim', {'for': 'python'}
Plug 'drewtempelmeyer/palenight.vim' " Color Scheme
Plug 'skywind3000/asyncrun.vim', {'for': 'python'} "For run command
Plug 'scrooloose/nerdtree' " NERDTree
Plug 'Xuyuanp/nerdtree-git-plugin' " Show git status flag
Plug 'tiagofumo/vim-nerdtree-syntax-highlight' " Sexy NERDTree icon.
Plug 'ryanoasis/vim-devicons' " Always be last one. Use for show sexy icon.

" End
" Initialize plugin system
call plug#end()

" Reload .vimrc and :PlugInstall to install plugins.

set nocompatible " Be Vi Improved
filetype on
filetype plugin on
filetype indent on
syntax on 
set t_Co=24 " Set truecolor
set showcmd " Show command that you type
" Hybrid number and Automatic toggling between line number modes
" When enter insert mode or buffer lose focus show absolute number
" Other time shows hybrid numbers.
:set number relativenumber

:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

" Control the position of the new window
:set splitbelow
:set splitright

" Move around split with CTRL + standard VIM movment key
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Change the leader from \ to ,
let mapleader="\,"

" For folding plugin
autocmd Filetype * AnyFoldActivate               " activate for all filetypes
set foldlevel=99 " Open all folds
hi Folded term=underline
let g:anyfold_identify_comments=2

" Enable folding with the space
nnoremap <Space> za

" Enable syntax highlighting for python(with polygot)
let g:python_highlight_all = 1

" Set encoding to UTF-8
set encoding=utf-8

" === Search === "
" ignore case when searching
set ignorecase

" if the search string has an upper case letter in it, the search will be case sensitive
set smartcase

" Automatically re-read file if a change was detected outside of vim
set autoread

" Yank and paste with the system clipboard
set clipboard=unnamed

" Hides buffers instead of closing them
set hidden

" Enable mouse
"set mouse=a

" Color Scheme
set background=dark
colorscheme palenight

" NERDTree CONFIGURATION
" Custom Icon for nerdtree-git-plugin
let g:NERDTreeIndicatorMapCustom = { 
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }

" Toggle NERDTree with <F5>
map <F5> :NERDTreeToggle<CR>

" Close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Ignore files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$']

" For Markdown Preview

" set to 1, nvim will open the preview window after entering the markdown buffer
" default: 0
let g:mkdp_auto_start = 1
" options for markdown render
" mkit: markdown-it options for render
" katex: katex options for math
" uml: markdown-it-plantuml options
" maid: mermaid options
" disable_sync_scroll: if disable sync scroll, default 0
" sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
"   middle: mean the cursor position alway show at the middle of the preview page
"   top: mean the vim top viewport alway show at the top of the preview page
"   relative: mean the cursor position alway show at the relative positon of the preview page
" hide_yaml_meta: if hide yaml metadata, default is 1
" sequence_diagrams: js-sequence-diagrams options
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {}
    \ }

" Mapping for Markdown Preview
nmap <leader>mp <Plug>MarkdownPreview
nmap <leader>mps <Plug>MarkdownPreviewStop

" For vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_theme='simple'

" For CtrlP
" CtrlP + ag and fzf + repgrep are very close plugin
" but fzf also is a shell fuzzy finder. choose whatever you want
" fzf + repgrep has dependency that i don't like.
" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" map uc to grep word under cursor
nnoremap <leader>uc :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
